import { CelestialBody, FAQItem, Faction, RankTier, Soundscape } from "@/types";

export const FACTIONS: Faction[] = [
  {
    id: "spacewalkers",
    name: "Spacewalkers",
    tagline: "Cosmic Lineage & Deep Work Focus",
    description:
      "An immersive deep-space focus surface. A slow-rotating planet at the center and a quiet orbital rail tracking your study sessions.",
    status: "active",
    accentColor: "#3CCBFF",
    features: ["Deep Work Mode", "Cinematic HUD", "Orbital Counter", "Ambient Soundscapes"],
  },
  {
    id: "pilots",
    name: "Pilots",
    tagline: "Structured Blueprint Sprints",
    description:
      "A structured blueprint workspace for sharp, scheduled study. Rigid Pomodoro blocks and a flight-itinerary progress rail.",
    status: "locked",
    accentColor: "#F4A940",
    features: ["Pomodoro Blocks", "Radar Map", "Checklist Tracker", "Blueprint Grid"],
  },
];

export const CELESTIAL_BODIES: CelestialBody[] = [
  {
    id: "sun",
    name: "Sun",
    hoursRequired: 0,
    xpBonus: 0,
    color: "#FCD34D",
    description: "The ignition origin of your deep work journey.",
    atmosphere: "Solar Plasma",
    distanceFromSun: "0 AU",
    funFact: "Contains 99.86% of all mass in the Solar System.",
  },
  {
    id: "mercury",
    name: "Mercury",
    hoursRequired: 1,
    xpBonus: 25,
    color: "#FF834E",
    description: "First orbital checkpoint closest to the sun.",
    atmosphere: "Exosphere",
    distanceFromSun: "0.39 AU",
    funFact: "A year on Mercury is just 88 Earth days.",
  },
  {
    id: "venus",
    name: "Venus",
    hoursRequired: 5,
    xpBonus: 75,
    color: "#E6B875",
    description: "Dense atmospheric concentration & deep work sprint.",
    atmosphere: "Carbon Dioxide & Sulfuric Acid",
    distanceFromSun: "0.72 AU",
    funFact: "Rotates in the opposite direction of most planets.",
  },
  {
    id: "earth",
    name: "Earth",
    hoursRequired: 15,
    xpBonus: 150,
    color: "#0083EE",
    description: "Home base milestone establishing core focus habits.",
    atmosphere: "Nitrogen & Oxygen",
    distanceFromSun: "1.00 AU",
    funFact: "The only known planet harboring deep focus & life.",
  },
  {
    id: "mars",
    name: "Mars",
    hoursRequired: 30,
    xpBonus: 300,
    color: "#FF5630",
    description: "The Red Planet endurance zone for persistent effort.",
    atmosphere: "Thin CO2",
    distanceFromSun: "1.52 AU",
    funFact: "Home to Olympus Mons, the largest volcano in the solar system.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    hoursRequired: 60,
    xpBonus: 600,
    color: "#F8A155",
    description: "Gas giant deep work masterclass with massive gravity.",
    atmosphere: "Hydrogen & Helium",
    distanceFromSun: "5.20 AU",
    funFact: "The Great Red Spot is a storm larger than Earth.",
  },
  {
    id: "saturn",
    name: "Saturn",
    hoursRequired: 100,
    xpBonus: 1000,
    color: "#EAB308",
    description: "Ring master focus perfectionist with iconic orbit rings.",
    atmosphere: "Hydrogen & Ammonia",
    distanceFromSun: "9.58 AU",
    funFact: "Has complex ring structures spanning thousands of miles.",
  },
  {
    id: "uranus",
    name: "Uranus",
    hoursRequired: 150,
    xpBonus: 1500,
    color: "#38BDF8",
    description: "Cyan ice giant with extreme axial tilt.",
    atmosphere: "Methane Ice",
    distanceFromSun: "19.22 AU",
    funFact: "Rotates almost completely on its side at 98 degrees.",
  },
  {
    id: "neptune",
    name: "Neptune",
    hoursRequired: 200,
    xpBonus: 2000,
    color: "#3B82F6",
    description: "Deep azure winds and supersonic atmospheric speed.",
    atmosphere: "Hydrogen & Methane",
    distanceFromSun: "30.05 AU",
    funFact: "Features the fastest winds in the solar system up to 1,200 mph.",
  },
  {
    id: "pluto",
    name: "Pluto",
    hoursRequired: 300,
    xpBonus: 3500,
    color: "#94A3B8",
    description: "Trans-Neptunian dwarf world of legendary focus.",
    atmosphere: "Nitrogen Ice",
    distanceFromSun: "39.48 AU",
    funFact: "Has a heart-shaped glacier named Tombaugh Regio.",
  },
  {
    id: "galaxy-core",
    name: "Galaxy Core",
    hoursRequired: 500,
    xpBonus: 8000,
    color: "#C7B8FF",
    description: "Cosmic singularity of infinite focus and mastery.",
    atmosphere: "Interstellar Plasma",
    distanceFromSun: "26,000 Light Years",
    funFact: "Supermassive black hole horizon surrounding billions of stars.",
  },
];

export const RANK_TIERS: RankTier[] = [
  { id: "trainee", name: "Trainee", tierNumber: 1, iconName: "Sparkles", xpRequired: 0 },
  { id: "astronaut", name: "Astronaut", tierNumber: 2, iconName: "Compass", xpRequired: 100 },
  { id: "explorer", name: "Explorer", tierNumber: 3, iconName: "Orbit", xpRequired: 300 },
  { id: "cosmonaut", name: "Cosmonaut", tierNumber: 4, iconName: "Rocket", xpRequired: 800 },
  { id: "starwalker", name: "Starwalker", tierNumber: 5, iconName: "Crown", xpRequired: 2000 },
];

export const SOUNDSCAPES: Soundscape[] = [
  { id: "cosmic-synth", name: "Cosmic Drone", category: "Deep Space", icon: "Radio", description: "Subtle low-frequency ambient synth pad." },
  { id: "solar-wind", name: "Solar Wind", category: "Nature FX", icon: "Wind", description: "Soft pink noise simulating cosmic atmospheric breeze." },
  { id: "deep-rain", name: "Orbital Rain", category: "White Noise", icon: "CloudRain", description: "Calming rain echoes inside an orbital capsule." },
  { id: "lofi-nebula", name: "Nebula Chill", category: "Lo-Fi Beats", icon: "Music", description: "Slow 60 BPM ambient study rhythm." },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    category: "General",
    question: "What makes FocusNebula different from standard study apps?",
    answer: "FocusNebula removes distracting dashboards and social clutter. Instead of gamifying distractive behavior, it provides an immersive WebGL space environment, orbit counters for deep focus, and local encrypted privacy.",
  },
  {
    category: "Factions",
    question: "What is the difference between Spacewalkers and Pilots?",
    answer: "Spacewalkers is built for long, continuous deep-work sessions with orbital progress tracking. Pilots is designed for structured Pomodoro sprints with rigid time blocks and task blueprints.",
  },
  {
    category: "Pricing",
    question: "Is FocusNebula free during the Beta?",
    answer: "Yes, FocusNebula Beta is completely free for authorized learners during our closed testing period. All progress logged during Beta will carry over to official release.",
  },
  {
    category: "Privacy",
    question: "How is my study data stored?",
    answer: "Your study logs and streak statistics are encrypted end-to-end and stored locally in your browser session.",
  },
];
